Repository SISE-Web-Development-Environments/assignment2-yuval_gal, pull requests merged in 2020-04, with the labels that each got.

#40 UglySettings
  css/main.css
  index.html
  js/app.js
Labels: Settings

#43 UglySettings
  audio/Blop sound effect.mp3
  audio/Extra.mp3
  audio/Fruit.mp3
  audio/PacMan Original Theme.mp3
  audio/blocker_hit.mp3
  audio/pacman_Pill.wav
  images/images.png
  images/pacmangirl.png
  images/pacmangirldown.png
  images/pacmangirlright.png
  images/pacmangirlup.png
  images/pill.png
  images/wall.PNG
  images/walls.png
  index.html
  js/app.js
Labels: Settings

#44 Add to registration page
  css/main.css
  images/logo.png
  index.html
  js/form-validation.js
  js/jquery.min.js
  js/jquery.validate.min.js
  js/validation.js
Labels: SignUp

#46 Show points
  .gitignore
  css/main.css
  index.html
  js/app.js
Labels: Game

#49 Ghost movement
  js/app.js
Labels: Ghosts

#50 Dave character
  images/dave.png
  images/daveLeft.png
  js/app.js
Labels: bugFix

#54 dave is working almost perfectly :) he doesnt always look the where h…
  images/daveDown.png
  images/daveUp.png
  js/app.js
Labels: Game

#58 Setting to left pane
  css/main.css
  index.html
  js/app.js
Labels: Settings

#82 Restart button
  css/main.css
  index.html
Labels: Settings
